### ISSUE TITLE
Failed when call method orders.GetOrder(OrderID);

### ISSUE THREAD

**Issue by elialber** [moip/moip-sdk-dotnet#10]
string orderId = "ORD-RY911RUY6EG6";
var order = client.Orders.GetOrder(orderId); //here broken

Failed to parse the response: Unexpected character encountered while parsing value: 
{. Path 'entries', line 1, position 3286"}

**Comment by araujo302** [comment]
I had the same problem :(

var order = client.Orders.GetOrder(orderID);
Failed to parse the response: Unexpected character encountered while parsing value: {. Path 'refunds', line 1, position 3396.}

**Comment by mbnakaya** [comment]
Hi guys!

The SDK has recently been updated and the problem seems to be fixed with the new version.
We were talking about it at #18.

Please make sure if this problem still happening.

## Download da nova versão
> By Package Manager
`PM> Install-Package Moip -Version 1.1.0`

> By .NET CLI
`> dotnet add package Moip --version 1.1.0`
