### ISSUE TITLE
Erro ao Criar Pagamento via Cartão de Crédito em PaymentResponse

### ISSUE THREAD

**Issue by andrevesdickow** [moip/moip-sdk-dotnet#15]
Boa tarde,

Estou com problema ao criar o pagamento via cartão de crédito. O pedido está criando, está retornando o Order Id, mas ao executar o pagamento, está retornando o erro "400 HTTP Response Not OK". Testei o pagamento via boleto, e criou o pedido e pagamento corretamente. O problema é na hora de fazer o pagamento via cartão.

Estamos usando a plataforma de e-commerce em .NET.

Obrigado e aguardo.

**Comment by andrevesdickow** [comment]
@bressani ??

**Comment by andrevesdickow** [comment]
@bressani @mbnakaya ??

**Comment by urso89** [comment]
Oi. Ontem estava tendo esse mesmo problema. Você descobriu o que era?

**Comment by andrevesdickow** [comment]
Olá @urso89 
Sim. na classe `PaymentRequest ` o campo `StatementDescriptor ` deve ser menor ou igual a 13 caracteres. Assim funcionou para mim.
Espero ter ajudado.
