### ISSUE TITLE
Valor do Frete não é enviado junto ao pagamento.

### ISSUE THREAD

**Issue by cidigitalagencia** [moip/moip-sdk-dotnet#16]
Estou utilizando a sdk DOTNET (dotnet add package Moip --version 1.0.1) que está divulgada neste link https://github.com/moip/moip-sdk-dotnet#instala%C3%A7%C3%A3o.

Bom estou realizando perfeitamente a compra através de cartão de crédito e também boleto, o pedido é criado com sucesso e também o código de pagamento é gerado perfeita.
O problema é que o valor do frete nunca é enviado para o MOIP.

No manual o código para enviar o frete esta descrito da seguinte maneira.
SubtotalsRequest subtotalsRequest = new SubtotalsRequest
{
    Shipping = 1500,
    Addition = 20,
    Discount = 10
};

Mas mesmo utilizando a SDK  indicada no manual eu nunca consigo fazer referência ao SubtotalsRequest, ele da um erro porque não consegue fazer referência a esta classe. 

![erro](https://user-images.githubusercontent.com/30224132/41741827-984a4f7e-7572-11e8-9373-2961208f3905.jpg)

Então, depois de muito tentar e reinstalar SDK eu consegui que ele não desse erro trabalhando desta forma.
Subtotals subtotalsRequest = new Subtotals
{
       Shipping = 3000,
       Addition = 1400
 };

![erro2](https://user-images.githubusercontent.com/30224132/41741978-094a4f12-7573-11e8-81d9-00fb4c4f78dd.jpg)

Dessa forma eu consigo fazer referência ao SubTotals mas ele envia apenas o Addition, ele não envia o valor do frete.

Resumindo todos os pedidos do meu site estão indo sem o valor do frete apenas o valor total dos itens mais o addition.

Entrei em contato com o suporte e fui informado que isto pode ser um BUG pois o addition esta indo e porque não consigo fazer referência ao SubtotalsRequest  sendo que estou utilizando a SDK correta??

Este problema esta me tirando o sono. Aguardo ajuda. Obrigado.

**Comment by matmiranda** [comment]
@cidigitalagencia tenho o mesmo problema, me parece que a classe `SubtotalsRequest` foi substituída por `Subtotals`.

**Comment by cidigitalagencia** [comment]
@matmiranda verdade, mas se utilizo o Subtotals, por mais que seja preenchido corretamente o valor do frete mesmo assim não é enviado. 
Acredito que não é enviado porque no AmoutOrderRequest não podemos passar o Subtotal.
Até o momento não tive retorno da MOIP sobre este problema.

**Comment by matmiranda** [comment]
Eu mesmo consegui, veja lá @cidigitalagencia

**Comment by cidigitalagencia** [comment]
@matmiranda , você conseguiu resolver?

**Comment by matmiranda** [comment]
@cidigitalagencia não :(

**Comment by matmiranda** [comment]
@cidigitalagencia essa biblioteca está cheio de erros, muito ruim

**Comment by mbnakaya** [comment]
Bom dia, pessoal. 

Nos desculpe pela demora no retorno.
Verifiquei os endpoints e os Models responsáveis pelas features do `/orders` e não consegui encontrar ou simular o erro apresentado.

Pelos meus testes, o nó **subtotals** está sendo adicionado corretamente ao **amount**, como podem observar:

![image](https://user-images.githubusercontent.com/32847427/42035773-1a2b2f30-7aba-11e8-8104-39666cbcde42.png)

![image](https://user-images.githubusercontent.com/32847427/42035910-6c3bca82-7aba-11e8-8491-42e4e52ddefd.png)

Eu utilizei exatamente o mesmo código do [exemplo](https://github.com/moip/moip-sdk-dotnet#cria%C3%A7%C3%A3o).

Poderiam nos mostrar o código da requisição completa que estão utilizando, por favor?

**Comment by cidigitalagencia** [comment]
@mbnakaya  eu tenho o mesmo do @matmiranda . Ele não reconhece o SubtotalsRequest.

**Comment by matmiranda** [comment]
@cidigitalagencia veja #18

**Comment by matmiranda** [comment]
@cidigitalagencia saiu nova atualização e não esquece de fechar "issues".

**Comment by matmiranda** [comment]
@mbnakaya fecha essa pergunta.
