### ISSUE TITLE
O nome do tipo ou do namespace "Order" não pode ser encontrado

### ISSUE THREAD

**Issue by matmiranda** [moip/moip-sdk-dotnet#18]
Segue o código:

```csharp
Client client = new Client("TOKEN_OAUTH", Configuration.Environments.SANDBOX);
string orderId = "ORD-HPMZSOM611M2";
Order order = client.Orders.GetOrder(orderId);
```

**Comment by mbnakaya** [comment]
O model foi importado corretamente?
```csharp
using Moip.Models;
```

**Comment by matmiranda** [comment]
@mbnakaya  Sim, parace que a biblioteca falhou pela nuget.

**Comment by matmiranda** [comment]
@mbnakaya  você já tentou usar biblioteca via NuGet (Moip version 1.0.1) ?

**Comment by mbnakaya** [comment]
Sim, eu utilizei o Package Manager do NuGet, via terminal.

Tente importar desta forma:
`PM> Install-Package Moip -Version 1.0.1`

**Comment by mbnakaya** [comment]
Como o motivo dos problemas que está tendo é o mesmo, aparentemente, vamos tratá-lo por essa issue. Conforme progredirmos, atualizamos as demais. Pode ser?

**Comment by urso89** [comment]
Esse problema ocorreu comigo também. Não consigo instanciar um objeto do tipo Order. Todos os outros eu consegui. Só ocorre esse problema com o Order.

**Comment by matmiranda** [comment]
@mbnakaya acabei de executar esse comando:

`PM> Install-Package Moip -Version 1.0.1`

Continua o mesmo problema, pode ver que está instalada corretamente:

![image](https://user-images.githubusercontent.com/24326905/42038215-c133cc8c-7ac0-11e8-8bad-ac670173704d.png)

**Comment by matmiranda** [comment]
@mbnakaya  O meu problema é tudo referenciado pelo `Moip.Models` que não está achando. Alguma coisa aconteceu com Models.

**Comment by mbnakaya** [comment]
Acabei de perceber, não existe uma classe `Order.cs`.

![image](https://user-images.githubusercontent.com/32847427/42038444-5b62d28a-7ac1-11e8-82cd-8b81d02acb1b.png)

**Há um erro no exemplo da documentação!**

Consegui fazer um GET em um pedido utilizando o seguinte método:
```csharp
OrderResponse getOrder = client.Orders.GetOrder(orderId);
```
Já que `Order` não é um tipo, e sim o método que retorna a instância do `OrdersController`.

**Comment by mbnakaya** [comment]
@matmiranda e @urso89, conseguiram resolver o problema com o método informado no comentário anterior?

**Comment by urso89** [comment]
Então, agora esta dando outro problema, com o retorno. Obrigado pelo exemplo @mbnakaya , eu entrei em outro post agora.
[https://github.com/moip/moip-sdk-dotnet/issues/10](url)
Se você souber como corrigir isso

**Comment by matmiranda** [comment]
@mbnakaya para consultar pedido, devo primeiro criar pedido, porem não consigo criar pedido, pode me ajudar [aqui](https://github.com/moip/moip-sdk-dotnet/issues/26).

**Comment by matmiranda** [comment]
Aqui consegui consultar normal :)

**Comment by matmiranda** [comment]
Para listar todos os pedidos eu fiz assim:

```csharp
OrderListResponse orderListResponse = client.Orders.ListOrders();
```

Porem retorna nada:

![image](https://user-images.githubusercontent.com/24326905/42045036-eb903406-7ad0-11e8-9cb0-5bc2e0051b80.png)

**Comment by urso89** [comment]
Então, no meu caso, estou tentando fazer o reembolso. O programador responsavel pela compra é outro rsrs... No meu caso, o meu retornar a OrderList, mas tentei o seu exemplo:

OrderResponse getOrder = client.Orders.GetOrder(orderId);

E ele dá esse problema:

Failed to parse the response: Unexpected character encountered while parsing value: {. Path 'entries', line 1, position 3001.

**Comment by mbnakaya** [comment]
@urso89 e @matmiranda, acredito ter encontrado o problema. Essas alterações estão disponíveis na branch master, mas não foram lançadas no release anterior. 😓

Darei inicio ao processo de release para que estas alterações fiquem disponíveis para download, via NuGet.

Nos desculpem por essa gafe.

**Comment by mbnakaya** [comment]
Pessoal, acabei de finalizar o release das novas atualizações!

### Download da nova versão
> Via Package Manager
`PM> Install-Package Moip -Version 1.1.0`

> Via .Net CLI
`> dotnet add package Moip --version 1.1.0`

Peço que verifiquem se os problemas apresentados são corrigidos com essa nova versão. Qualquer problema relacionado ao mesmo, basta comentar nesta mesma issue, por favor.

Nos desculpem mais uma vez pelo transtorno. E obrigado pela compreensão. 😃🚀

**Comment by urso89** [comment]
Muito obrigado!

**Comment by urso89** [comment]
Aqui o problema permanece
![moip](https://user-images.githubusercontent.com/32397071/42113500-d7e48492-7bc1-11e8-8699-e8cc43d263c5.png)

**Comment by matmiranda** [comment]
Aqui funcionou direitinho 😆

**Comment by matmiranda** [comment]
@urso89 Pela a foto está tudo certo.

**Comment by matmiranda** [comment]
@urso89 ,,

A [documentação ](https://github.com/moip/moip-sdk-dotnet#consulta)está errada.

O correto é assim:

```csharp
string orderId = "ORD-HPMZSOM611M2";
OrderResponse getOrder = client.Orders.GetOrder(orderId);
```

**Comment by matmiranda** [comment]
@mbnakaya pode me liberar para eu corrigir a documentação ?

**Comment by mbnakaya** [comment]
@matmiranda, obigado por toda a ajuda! 👍🚀

Não preciso te liberar acesso para commitar nas branchs. Se desejar, basta abrir um PR que eu revisarei e aprovarei as alterações. 😃

**Comment by mbnakaya** [comment]
Como o problema foi aparentemente sanado, vou fechar esta issue. No entanto, fiquem à vontade para comentar ou reabri-la, se acharem necessário.
