### ISSUE TITLE
Corrigir documentação

### ISSUE THREAD

**Issue by matmiranda** [moip/moip-sdk-dotnet#19]
Na documentação está errada: https://github.com/moip/moip-sdk-dotnet#boleto

O correto é assim:

```
BoletoInstructionLines boletoInstructionLines = new BoletoInstructionLines
{
    First = "Primeira linha",
    Second = "Segunda linha",
    Third = "Terceira linha"
};
```
Sem parenteses "( )" e colocar igual "=" .

Erros:

> O nome "First" não existe no contexto atual
> O nome "Second" não existe no contexto atual
> O nome "Third" não existe no contexto atual

**Comment by mbnakaya** [comment]
Tem razão, @matmiranda!

Muito obrigado pelo aviso! 🚀
