### ISSUE TITLE
O nome do tipo ou do namespace "Payment" não pode ser encontrado

### ISSUE THREAD

**Issue by matmiranda** [moip/moip-sdk-dotnet#20]
Segue a documentação: https://github.com/moip/moip-sdk-dotnet#boleto

Na última linha:

`Payment payment = client.Payments.CreateBoletoOrDebit("ORD-GOHHIF4Z6PLV", paymentRequest);`

Recebo erro:

> O nome do tipo ou do namespace "Payment" não pode ser encontrado (está faltando uma diretiva using ou uma referência de assembly?)

**Comment by mbnakaya** [comment]
@matmiranda 

Verifique os imports! Sem utilizar o `using` apropriado, o compilador não conseguirá identificar as classes importadas da SDK.

```csharp
using Moip.Models;
```

Utilizando este trecho ☝️ já deve resolver o seu problema.

**Comment by matmiranda** [comment]
@mbnakaya não funciona usando `using Moip.Models`, veja a imagem:

![image](https://user-images.githubusercontent.com/24326905/42037899-d9d9fd48-7abf-11e8-887c-918d9c0bf4cd.png)

Tem alguma coisa errada nessa biblioteca via nuget.

**Comment by matmiranda** [comment]
@mbnakaya Porque fechou ?

**Comment by mbnakaya** [comment]
Ao meu ver, a maioria dos problemas relatados em todas as issues que você abriu decorrem do mesmo motivo, visto que a mensagem de erro é a mesma, só muda a classe em questão. Com isso, é realmente necessário manter todas essas issues abertas simultaneamente?

Imagino que o progresso em uma destas issues refletirá em todas as outras semelhantes. Por motivos de organização e para diminuir a complexidade, acredito que o ideal seja focar em um dos problemas e, na mesma issue, relatar quais são os outros semelhantes. Assim, não precisaremos de várias treads para o mesmo problema. 😃

E, caso o problema ainda se apresente em outros pontos, aí faz mais sentido iniciarmos outra issue para analisarmos as excessões. Entendo que dessa forma podemos evitar replicar mensagens. 👍

**Comment by matmiranda** [comment]
Faz sentido, você tem toda razão.
