### ISSUE TITLE
Problema para criar Subtotals na criação do pedido

### ISSUE THREAD

**Issue by andrevesdickow** [moip/moip-sdk-dotnet#25]
Bom dia,

Estou criando a variável Subtotals com o SDK .NET do Moip. Tenho instalado a versão 1.0.1, via Nuget. Porém, não está reconhecendo uns campos, conforme está na documentação.
Abaixo o código que está na documentação:

```
SubtotalsRequest subtotalsRequest = new SubtotalsRequest
{
    Shipping = 1500,
    Addition = 20,
    Discount = 10
};

AmountOrderRequest amountRequest = new AmountOrderRequest
{
    Currency = "BRL"
    Subtotals = subtotalsRequest
};
```

Isso pode ser encontrado aqui: https://github.com/moip/moip-sdk-dotnet#criação

Porém nesta última versão instalada, a classe SubtotalsRequest está como Subtotals e não é possível adicionar Subtotals em AmountOrderRequest, como está na documentação, apenas o campo Currency.

Abaixo o link do print do problema:
https://v2uploads.zopim.io/3/4/4/344xoFdKytIkRoXelxnI8N9CpVaAfSDl/0f586504cd9783adab0f595b2743e694da420307.png

Podem verificar se foi atualizado ou se este parâmetro é passado em outro lugar??

Obrigado e aguardo.

**Comment by mbnakaya** [comment]
Bom dia, @andrevesdickow 

Estranho, pois consegui utilizar o `Subtotals`, sem menores problemas, na última versão do SDK.

![image](https://user-images.githubusercontent.com/32847427/42042272-2b44af52-7aca-11e8-89b3-e6bc51728357.png)

Por favor, tente utilizar o Package Manager do NuGet para baixar o SDK.
```
PM> Install-Package Moip -Version 1.0.1
```

Devido aos recentes casos, acredito estar havendo algum problema na instação via NuGet, descrito no [exemplo](https://github.com/moip/moip-sdk-dotnet#instala%C3%A7%C3%A3o) da documentação.

**Comment by andrevesdickow** [comment]
Fala @mbnakaya, tudo certo?

Desinstalei a versão do Moip (que era a mesma - 1.0.1) e reinstalei pelo comando que você me enviou. Está ocorrendo o mesmo problema ainda.

Podes conferir se esta versão que você está mandando no print está publicado no Nuget? Ou se está na versão 1.0.0?

Ainda não está aparecendo a classe SubtotalsRequest, apenas Subtotals, conforme imagem que mandei anteriormente e também ainda não aparece o Subtotals em AmountOrdeRequest.

Obrigado e aguardo.

**Comment by matmiranda** [comment]
@mbnakaya na sua imagem que você postou, está como `SubtotalsRequest`, aqui aparece somente `Subtotals`:

![image](https://user-images.githubusercontent.com/24326905/42047098-beee8e20-7ad5-11e8-92f5-58cee60718e7.png)

**Comment by matmiranda** [comment]
Boa noite @andrevesdickow,

Saiu nova atualização 1.1.0.

Veja se o problema foi resolvido e não esquece de fechar "issues".

**Comment by andrevesdickow** [comment]
Bom dia @matmiranda 
Agora está está funcionando perfeitamente. 
Muito obrigado! 😁
