### ISSUE TITLE
Ontem estava sem esse Erro "Ocorreu um erro ao enviar a solicitação"

### ISSUE THREAD

**Issue by urso89** [moip/moip-sdk-dotnet#27]
Ontem estava no pc, tentando implementar o reembolso no sistema da empresa em que trabalho, desliguei o pc e fui pra casa. Quando voltei hoje, e tentei novamente, me surgiu esse erro. Voltei o código anterior para ver se isso resolveria o problema, porém continuou.

Response Erro 500 - Mensagem "Ocorreu um erro ao enviar a solicitação"

Alguém pode me dar uma luz sobre o assunto?

**Comment by matmiranda** [comment]
Erro 500 é erro no servidor, você deve falar com eles via chat, para ver o que está acontecendo.

**Comment by mbnakaya** [comment]
Boa, @matmiranda!

@urso89, pode ser que tenha ocorrido alguma instabilidade em nossas APIs. Já que esta é uma resposta retornada por algum endpoint que você requisitou. Quando ocorrer este tipo de problema, relacionado à API, pode entrar em contato com o nosso time de suporte pelo `integracao@moip.com.br` (via ticket) ou pelo [chat](https://dev.moip.com.br/), para maiores informações.

O problema mencionado persiste?

**Comment by urso89** [comment]
>

**Comment by urso89** [comment]
Então, esse erro não aconteceu mais, mas agora ocorre outro. 
"A solicitação foi anulada: Não foi possível criar um canal seguro para SSL/TLS."
Mas isso ocorre em ambiente sandbox.

**Comment by mbnakaya** [comment]
@matmiranda, novamente é uma mensagem retornada pela API. Isso significa que seu SSL/TLS está desatualizado e precisa ser atualizado para o protocolo de segurança `TLS 1.2`, por exigência do **PCI**. Se observar, colocamos avisos com informações em todas as páginas do `dev.moip.com.br`.

Se sentir a necessidade de obter mais informação sobre a atualização do TLS, além das informações colocadas nos avisos, ou sobre qualquer outro ponto relacionado à nossa API, recomendo que entre em contato com nosso time de integração. Os meios de contato estão no meu último comment. ☝️

**Comment by urso89** [comment]
Ok, obrigado @mbnakaya pelo retorno. Vou entrar em contato com eles.

**Comment by mbnakaya** [comment]
Sobre qualquer problema relacionado ao SDK, fico à disposição para ajudar como puder.

**Comment by urso89** [comment]
Tenho uma dúvida sobre o sdk. Estou tentando reproduzir erros para poder tratar quando acontecer, e não estou conseguindo pegar os códigos de erro.
Quando crio um RefundCCResponse, e acontece um erro, ele cai direto no catch, e estou utilizando o APIException do Moip. No exception, onde eu consigo encontrar as mensagens, e os códigos dos erros?

O ResponseCode e Message do exception, estão vindo com códigos HTTP, e mensagem HTTP. Tipo eu tento fazer um reembolso pela segunda vez de um que já foi feito, ele traz o código "HTTP not response" erro 400. Eu tento fazer um reembolso com OrderId vazio, ele retorna ResponseCode 405. Tentei reproduzir erros utilizando cpf de outra pessoa em um orderid de outro, e não gerou erro, e outros.

**Comment by RodrigoQuintas** [comment]
Sobre o erro **"A solicitação foi anulada: Não foi possível criar um canal seguro para SSL/TLS."**

Basta adicionar a seguinte linha de código no construtor da classe HTTPClient:
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`
