### ISSUE TITLE
Verificar se usuário já possui Conta Moip

### ISSUE THREAD

**Issue by matmiranda** [moip/moip-sdk-dotnet#28]
O métdo `CheckAccountExists` nunca vai retornar false quando o CPF ou CNPJ não existir.

```csharp
bool AccountExistsFromMoip = client.Accounts.CheckAccountExists("123.456.798-93");
//dessa forma gera uma exceção
```

Tenho que fazer isso:

```csharp
try
{
    bool AccountExistsFromMoip = client.Accounts.CheckAccountExists("123.456.798-93");
}
catch (APIException ex)
{
    if (ex.ResponseCode == 400)
    {
        //CPF ou CNPJ não existe
        return false;
    }
}
```

**Comment by mbnakaya** [comment]
@matmiranda, este comportamento diferenciado vem da API de `/accounts`. Ela trata os diferentes cenários da seguinte forma:

| StatusCode | ResponseBody | Result |
| :---: | :---: | :---: |
| 200 | 200 | Exist |
| 400 | 400 | Invalid document |
| 404 | 404 | Does Not Exist |

Implementamos algumas soluções para tratar este endpoint, como na [SDK de Java](https://github.com/moip/moip-sdk-java/blob/master/src/main/java/br/com/moip/api/AccountAPI.java#L36), por exemplo.

Atualmente, a SDK de .NET não dispõe de um tratamento mais eficiente para este tipo de contexto. Mas estamos trabalhando para reformular esta solução, igualando às outras SDKs que oferecemos, em termos de features.
