### ISSUE TITLE
Pergunta: Token_oAUth

### ISSUE THREAD

**Issue by elialber** [moip/moip-sdk-dotnet#8]
Olá Moip,

como gerar o token_oauth
Client client = new Client("TOKEN_OAUTH", Configuration.Environments.SANDBOX);

Grato.

**Comment by somentelucas** [comment]
Oi @elialber, você pode ver como gerar o token oauth nessa página da documentação sobre [criar App](https://documentao-moip.readme.io/v2.0/reference#1-criar-um-app).

O access token é retornado na criação do App.
